source("data-raw/monta_usinas.r", encoding = "UTF-8")
source("data-raw/monta_verificado_ccee.r", encoding = "UTF-8")
source("data-raw/add_cap_inst_futura.r", encoding = "UTF-8")
#source("data-raw/monta_reanalise.r", encoding = "UTF-8")
source("data-raw/interpola_reanalise.r", encoding = "UTF-8")